    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: fintech-ingress
      namespace: fintech-app
      annotations:
        kubernetes.io/ingress.class: "gce"
        networking.gke.io/managed-certificates: "fintech-managed-cert"
        kubernetes.io/ingress.global-static-ip-name: "fintech-ingress-ip"  
    spec:
      defaultBackend:
        service:
          name: nginx-service
          port:
            number: 80
